declare -a examples=("apply_force"
                     "body_types"
                     "box_cutter"
                     "breakable"
                     "bridge"
                     "bullet"
                     "cantilever"
                     "car"
                     "chain"
                     "character_collision"
                     "cloth"
                     "collision_filtering"
                     "collision_processing"
                     "confined"
                     "convex_hull"
                     "conveyor_belt"
                     "distance"
                     "edge_shapes"
                     "edge_test"
                     "empty"
                     "gish_tribute"
                     "liquid"
                     "mobile"
                     "motor_joint"
                     "one_sided_platform"
                     "pinball"
                     "pulley"
                     "pyramid"
                     "raycast"
                     "restitution"
                     "rope"
                     "settings"
                     "theo_jansen"
                     "tiles"
                     "time_of_impact"
                     "top_down_car"
                     "tumbler"
                     "vertical_stack"
                     "web"
                     )


python -m examples.hello >/dev/null

for ex_name in "${examples[@]}"
do
    python -m "examples.$ex_name" --backend=pyglet --onlyInit
done
