# vi: sw=2 ts=2 sts=2

package:
  name: pybox2d
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'unknown') }}post{{ environ.get('GIT_DESCRIBE_NUMBER','') }}

source:
  git_url: https://github.com/pybox2d/pybox2d
  git_rev: master

build:
  number: 0

requirements:
  build:
    - python
    - swig >=3

  run:
    - python

test:
  imports:
    - Box2D
    - Box2D.b2

  commands:
    - cd $SRC_DIR
    - nosetests -v tests
    - $RECIPE_DIR/example_tests.sh  # [unix]
    - $RECIPE_DIR/example_tests.cmd  # [win]

  requires:
  - nose
  - pyglet

about:
  home: http://github.com/pybox2d/pybox2d
  license: zlib
  summary: 'Python Box2D'
