# vi: sw=2 ts=2 sts=2 expandtab

package:
  name: pygame_sdl2
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'unknown').replace('renpy-', '') }}plus{{ environ.get('GIT_DESCRIBE_NUMBER','') }}

source:
  # git_url: https://github.com/renpy/pygame_sdl2
  git_url: https://github.com/kne/pygame_sdl2
  git_branch: process_namehint_py3k

build:
  number: 0

# NOTE: A bunch of OS-specific build requirements are not listed here.
#       See build.sh, which attempts to install (or at least check) for those.
requirements:
  build:
    - setuptools
    - python
    - cython
  run:
    - python

test: 
  imports:
    - pygame_sdl2.color
    - pygame_sdl2.display
    - pygame_sdl2.draw
    - pygame_sdl2.event
    - pygame_sdl2.font
    - pygame_sdl2.gfxdraw
    - pygame_sdl2.image
    - pygame_sdl2.joystick
    - pygame_sdl2.key
    - pygame_sdl2.locals
    - pygame_sdl2.mixer
    - pygame_sdl2.mouse
    - pygame_sdl2.scrap
    - pygame_sdl2.sprite
    - pygame_sdl2.surface
    - pygame_sdl2.sysfont
    - pygame_sdl2.time
    - pygame_sdl2.transform
    - pygame_sdl2.version


  # commands:
  #   - cd $SRC_DIR
  #   - python setup.py test
  
about:
  home: http://pygame-sdl2.readthedocs.org/
  license: LGPL2
